// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hflxgbpaownishntdlkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhmbHhnYnBhb3duaXNobnRkbGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzOTM2MDMsImV4cCI6MjA3Mzk2OTYwM30.JUvVzL88IiEyRSvKyZWnoGTfa1kL8Ft3jsKtBehqgsw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});